(() => {
 const cfg=window.CARLA_SUPABASE||{}; const configured=cfg.url&&cfg.anonKey&&!cfg.url.startsWith('YOUR_');
 const loginPanel=document.querySelector('#login-panel'),dashboard=document.querySelector('#dashboard'),list=document.querySelector('#review-list'),signOut=document.querySelector('#sign-out');
 if(!configured){document.querySelector('#login-status').textContent='Supabase is not connected yet. Complete REVIEW-SYSTEM-SETUP.md first.';return}
 const db=window.supabase.createClient(cfg.url,cfg.anonKey); let reviews=[],filter='pending';
 const esc=v=>String(v??'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]));
 async function isAdmin(){const {data:{user}}=await db.auth.getUser();if(!user)return false;const {data}=await db.from('admin_users').select('user_id').eq('user_id',user.id).maybeSingle();return !!data}
 async function syncAuth(){const ok=await isAdmin();loginPanel.hidden=ok;dashboard.hidden=!ok;signOut.hidden=!ok;if(ok)await load()}
 document.querySelector('#login-form').addEventListener('submit',async e=>{e.preventDefault();const email=new FormData(e.currentTarget).get('email');const status=document.querySelector('#login-status');const {error}=await db.auth.signInWithOtp({email,options:{emailRedirectTo:`${location.origin}${location.pathname}`}});status.textContent=error?error.message:'Check your email for the secure sign-in link.'});
 signOut.addEventListener('click',async()=>{await db.auth.signOut();location.reload()});document.querySelector('#refresh').addEventListener('click',load);
 document.querySelectorAll('.tabs button').forEach(btn=>btn.addEventListener('click',()=>{document.querySelectorAll('.tabs button').forEach(x=>x.classList.remove('active'));btn.classList.add('active');filter=btn.dataset.filter;render()}));
 async function load(){const {data,error}=await db.from('reviews').select('*').order('created_at',{ascending:false});if(error){list.innerHTML=`<div class="empty">${esc(error.message)}</div>`;return}reviews=data||[];['pending','approved','archived'].forEach(s=>document.querySelector(`#${s}-count`).textContent=reviews.filter(r=>r.status===s).length);render()}
 function render(){const rows=filter==='all'?reviews:reviews.filter(r=>r.status===filter);if(!rows.length){list.innerHTML='<div class="empty">No reviews in this group.</div>';return}list.innerHTML=rows.map(r=>`<article class="admin-review" data-id="${r.id}"><div class="admin-review-head"><div><h3>${esc(r.reviewer_name)}</h3><div class="stars">${'★'.repeat(r.rating)}${'☆'.repeat(5-r.rating)}</div></div><span class="badge ${r.status}">${r.status}</span></div><p class="private-email">Private email: ${esc(r.reviewer_email)} · ${esc(r.category)} · Submitted ${new Date(r.created_at).toLocaleString()}</p><p class="review-copy">${esc(r.review_text)}</p><div class="actions">${r.status!=='approved'?'<button class="approve" data-action="approve">Approve & publish</button>':'<button class="archive" data-action="archive">Unpublish</button>'}<button class="ghost" data-action="edit">Edit</button>${r.status!=='archived'?'<button class="archive" data-action="archive">Archive</button>':''}<button class="danger" data-action="delete">Delete</button></div></article>`).join('')}
 list.addEventListener('click',async e=>{const btn=e.target.closest('button[data-action]');if(!btn)return;const id=btn.closest('[data-id]').dataset.id,r=reviews.find(x=>String(x.id)===id),action=btn.dataset.action;if(action==='edit'){openEdit(r);return}if(action==='delete'&&!confirm('Permanently delete this review?'))return;let query;if(action==='delete')query=db.from('reviews').delete().eq('id',id);else if(action==='approve')query=db.from('reviews').update({status:'approved',approved_at:new Date().toISOString()}).eq('id',id);else query=db.from('reviews').update({status:'archived',featured:false}).eq('id',id);const {error}=await query;if(error)alert(error.message);else load()});
 const dialog=document.querySelector('#edit-dialog'),editForm=document.querySelector('#edit-form');function openEdit(r){editForm.id.value=r.id;editForm.reviewer_name.value=r.reviewer_name;editForm.category.value=r.category;editForm.rating.value=r.rating;editForm.review_text.value=r.review_text;editForm.featured.checked=!!r.featured;dialog.showModal()}
 document.querySelector('#save-edit').addEventListener('click',async e=>{e.preventDefault();const v=Object.fromEntries(new FormData(editForm));const {error}=await db.from('reviews').update({reviewer_name:v.reviewer_name,category:v.category,rating:Number(v.rating),review_text:v.review_text,featured:Boolean(v.featured)}).eq('id',v.id);if(error)alert(error.message);else{dialog.close();load()}});
 db.auth.onAuthStateChange(()=>setTimeout(syncAuth,0));syncAuth();
})();
